with-expecter: true
packages:
  github.com/cirrostratus-cloud/common/event:
    interfaces:
      EventBus:
  github.com/cirrostratus-cloud/common/email:
    interfaces:
      EmailService:
  github.com/cirrostratus-cloud/auth/user:
      interfaces:
        UserRepository: